language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - python -m unittest tests
    - coverage run --source=wpadmin tests.py
after_success: coveralls
